### ISSUE TITLE
Sense plugin broke after the 82.0 upgrade

### ISSUE THREAD

**Issue by theOrakle** [robbiet480/Home-Assistant-Config#2]
```
Nov 13 07:21:18 bridge hass[22767]: 2018-11-13 07:21:18 ERROR (MainThread) [homeassistant.setup] Error during setup of component sense
Nov 13 07:21:18 bridge hass[22767]: Traceback (most recent call last):
Nov 13 07:21:18 bridge hass[22767]:   File "/opt/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
Nov 13 07:21:18 bridge hass[22767]:     component.setup, hass, processed_config)  # type: ignore
Nov 13 07:21:18 bridge hass[22767]:   File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
Nov 13 07:21:18 bridge hass[22767]:     yield self  # This tells Task to wait for completion.
Nov 13 07:21:18 bridge hass[22767]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
Nov 13 07:21:18 bridge hass[22767]:     future.result()
Nov 13 07:21:18 bridge hass[22767]:   File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
Nov 13 07:21:18 bridge hass[22767]:     raise self._exception
Nov 13 07:21:18 bridge hass[22767]:   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Nov 13 07:21:18 bridge hass[22767]:     result = self.fn(*self.args, **self.kwargs)
Nov 13 07:21:18 bridge hass[22767]:   File "/opt/homeassistant/lib/python3.5/site-packages/homeassistant/components/sense.py", line 39, in setup
Nov 13 07:21:18 bridge hass[22767]:     username = config[DOMAIN][CONF_EMAIL]
Nov 13 07:21:18 bridge hass[22767]: KeyError: 'sense'
```

**Comment by robbiet480** [comment]
[Sense shutdown in 2017](https://t.co/dIBmnqTG00) and servers went offline shortly thereafter. Not sure what data you were still seeing.
